channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.9
  - scipy
  - pandas
  - numpy
  - statsmodels
  - metpy
  - jupyter
  - scikit-learn
  - plotly
  - pingouin
  - sqlalchemy
  - matplotlib
  - affine
  - rasterio
  - refet
