[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "micromet"
version = "0.3.0"
description = "A microclimate analysis tool"
authors = [
    { name = "Paul Inkenbrandt", email = "paulinkenbrandt@utah.gov" }
]
license = { text = "MIT" }
requires-python = ">=3.9"

[project.dependencies]
pandas = "^1.2.0"
numpy = "^1.19.5"
matplotlib = "^3.3.3"
scipy = "^1.6.0"
statsmodels = "^0.14.0"
scikit-learn = "^1.4.0"
plotly = "^2.35.0"
affine = "^2.2.0"
rasterio = "^1.2.0"

[project.optional-dependencies]
dev = [
    "pytest>=6.2.2",
    "black>=20.8b1",
    "flake8>=3.8.4"
]

[project.urls]
homepage = "https://github.com/utah-geological-survey/MicroMet"
repository = "https://github.com/utah-geological-survey/MicroMet"
