name: Publish to Conda

on:
  push:
    branches:
      - '**'  # Matches all branches
  workflow_dispatch:  # Keeping manual trigger option

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetches all history for all branches and tags

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.10"  # Specify exact Python version
        channels: conda-forge,defaults
        channel-priority: strict
        activate-environment: build-env

    - name: Install dependencies
      run: |
        conda install conda-build anaconda-client boa -c conda-forge
        conda info
        conda list

    - name: Build conda package
      run: |
        # Get the current git hash for version tracking
        GIT_HASH=$(git rev-parse --short HEAD)
        echo "GIT_HASH=$GIT_HASH" >> $GITHUB_ENV
        conda mambabuild conda-recipe/ --output-folder ./conda-dist/

    - name: Publish to Conda
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'  # Only publish from main/master
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        anaconda upload --force ./conda-dist/**/*.tar.bz2
